ading sso urls and setup
praekeltfoundation/molo-tuneme pull request #346
Opened 2016-12-01 04:51 UTC by codiebeulaine

2016-12-01 04:52 UTC, codiebeulaine commented
@saeedmb8 ready for review

2016-12-05 16:29 UTC, smarzban requested changes

2016-12-05 16:29 UTC, saeedmb8 commented on tuneme/tests/test_sessions.py
> +import time
Please remove this test

2016-12-05 16:42 UTC, smarzban approved these changes

2016-12-05 16:42 UTC, saeedmb8 commented
👍

2016-12-05 16:46 UTC, merged